name: morecycles
version: 0.1.0.0
synopsis: Pattern manipulation (or generation) functions for TidalCycles that have musical value but aren't (yet) part of TidalCycles
description: See morecycles.pdf
maintainer: Quint Guvernator <quint@guvernator.net>
category: Music

ghc-options: -Wall

dependencies:
  - QuickCheck
  - base
  - containers
  - directory
  - lens
  - mtl
  - parsec
  - random
  - template-haskell
  - tidal

library:
  source-dirs: lib

tests:
  jumbletests:
    main: jumbletests.lhs
    source-dirs: test
    dependencies:
      - morecycles
      - QuickCheck
      - hspec
      - tidal

  jittertests:
    main: jittertests.lhs
    source-dirs: test
    dependencies:
      - morecycles
      - QuickCheck
      - hspec
      - tidal
      - random

  arrhythmiatests:
    main: arrhythmiatests.lhs
    source-dirs: test
    dependencies:
      - morecycles
      - QuickCheck
      - hspec
      - tidal

  rhythmasktests:
    main: rhythmasktests.lhs
    source-dirs: test
    dependencies:
      - morecycles
      - QuickCheck
      - hspec
      - tidal

  gracenotes:
    main: gracenotestests.lhs
    source-dirs: test
    dependencies:
      - morecycles
      - QuickCheck
      - hspec
      - tidal
