name: morecycles
version: 0.1.0.0
synopsis: My Haskell project
description: See morecycles.pdf
maintainer: My Name <my.email@example.com>
category: Logic

ghc-options: -Wall

dependencies:
  - QuickCheck
  - base
  - containers
  - directory
  - lens
  - mtl
  - parsec
  - random
  - template-haskell
  - tidal

library:
  source-dirs: lib

executables:
  myprogram:
    main: Main.lhs
    source-dirs: exec
    dependencies:
      - morecycles

tests:
  simpletests:
    main: simpletests.lhs
    source-dirs: test
    dependencies:
      - morecycles
      - QuickCheck
      - hspec
